services:
  calculator-bot:
    build: ../AdvancedCalculaterBot
    container_name: advanced-calculator-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOTTOKEN=${TELEGRAM_BOTTOKEN_CALC}
      - ADMIN_IDS=${ADMIN_IDS_CALC}
      - PORT=5001
    ports:
      - "5001:5001"

  cloudflare-bot:
    build: ../CloudflareWorkerBot
    container_name: cloudflare-worker-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOTTOKEN=${TELEGRAM_BOTTOKEN_CF}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - PORT=5002
    ports:
      - "5002:5002"

  youtube-bot:
    build: ../YouTubeDownloaderBot
    container_name: youtube-downloader-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOTTOKEN=${TELEGRAM_BOTTOKEN_YT}
      - PORT=5000
    ports:
      - "5000:5000"